#! /usr/bin/env python3
import sys
import signal
import argparse

from pijuice_histograms.collector import DatapointCollector


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "PATH",
        help="Path to the sqlite file where the data will be stored."
    )

    args = parser.parse_args()

    collector = DatapointCollector(args.PATH)

    def exit_gracefully(*args):
        collector.save()
        collector.close()
        sys.exit(0)

    signal.signal(signal.SIGINT, exit_gracefully)
    signal.signal(signal.SIGTERM, exit_gracefully)

    try:
        collector.run()
    except KeyboardInterrupt:
        collector.save()
        collector.close()
        sys.exit(0)
