#! /usr/bin/env python3
import sys
import os.path
import argparse

from pijuice_histograms.generator import generate_webpage_for_last_month


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "SQLITE_PATH",
        help="Path to the sqlite file with datapoints."
    )
    parser.add_argument(
        "REPORT_PATH",
        help="Path to the directory where the report will be stored."
    )

    args = parser.parse_args()

    if not os.path.exists(args.SQLITE_PATH):
        sys.stderr.write(f"`{args.SQLITE_PATH}` doesn't exists!\n")
        sys.exit(1)

    generate_webpage_for_last_month(args.SQLITE_PATH, args.REPORT_PATH)
