#! /usr/bin/env python3
import sys
import os.path
import argparse

from pijuice_histograms import DatapointCollector


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "PATH",
        help="Path to the sqlite file where the data will be stored."
    )

    args = parser.parse_args()

    collector = DatapointCollector(args.PATH)

    try:
        collector.run()
    except KeyboardInterrupt:
        collector.save()
        sys.exit(0)
