#! /usr/bin/env python3
import sys
import os.path
import argparse

from pijuice_histograms.generator import _print_all_values


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "PATH",
        help="Path to the sqlite file where the data will be stored."
    )

    args = parser.parse_args()

    if not os.path.exists(args.PATH):
        sys.stderr.write(f"`{args.PATH}` doesn't exists!\n")
        sys.exit(1)

    _print_all_values(args.PATH)
